subscriber_template = {
    "id": "cuy36rzagy6sauxvowko",
    "href": "https://api.getdrip.com/v2/2289396/subscribers/cuy36rzagy6sauxvowko",
    "status": "active",
    "email": "personnel@vrt.fi",
    "first_name": "Personnel",
    "last_name": "Dude",
    "address1": None,
    "address2": None,
    "city": "Jyväskylä",
    "state": None,
    "zip": "40660",
    "phone": None,
    "country": "Finland",
    "time_zone": None,
    "utc_offset": 0,
    "visitor_uuid": None,
    "custom_fields": {},
    "tags": [],
    "created_at": "2019-08-13T07:41:19Z",
    "ip_address": None,
    "user_agent": None,
    "lifetime_value": None,
    "original_referrer": None,
    "landing_url": None,
    "prospect": None,
    "base_lead_score": None,
    "eu_consent": "unknown",
    "lead_score": None,
    "user_id": None,
    "links": {"account": "2289396"}
}
